[package]
name = "optional-trait-methods"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2024"

[features]
default = ["target_advanced", "using_traits"]

bench = []

using_options = []
using_fn = []
using_traits = []

target_basic = []
target_advanced = []
target_faulty = []

[dependencies]
libc = { version = "0.2", default-features = false }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
rand_chacha = { version = "0.3", default-features = false }

[profile.release]
panic = "abort"
opt-level = "s"

[profile.dev]
panic = "abort"
