[package]
name = "optional-trait-methods"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2024"

[features]
default = ["target_advanced", "using_traits", "always_inline"]

always_inline = []
interpretable_asm = []
dce_markers = []
bench = []
traits_codegen_cases = []

using_cfg_gates = []
using_is_supported = []
using_options = []
using_fn = []
using_traits = []
using_try_as_dyn = []

target_basic = []
target_advanced = []
target_faulty = []

[dependencies]
libc = { version = "0.2", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
rand_core = { version = "0.6", default-features = false }

[[bin]]
name = "idet-cases-bench"
path = "src/bin/idet_cases_bench.rs"
required-features = ["using_traits", "traits_codegen_cases"]

[profile.release]
panic = "abort"
opt-level = "s"
codegen-units = 1

[profile.dev]
panic = "abort"
